import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // Edge functions are Deno, not browser code: they legitimately use Deno globals,
    // import by URL, and pass through untyped third-party API payloads. Linting them
    // with the browser config produced ~90 errors that said nothing about their
    // correctness. Real bugs (unused vars aside) are still reported.
    files: ["supabase/functions/**/*.ts"],
    languageOptions: {
      globals: { Deno: "readonly", EdgeRuntime: "readonly" },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "no-undef": "off",
    },
  },
  {
    // Generated by the shadcn CLI — see CLAUDE.md. Empty interfaces that extend a
    // primitive's props are part of that generated shape, not a defect to fix here.
    files: ["src/components/ui/**/*.tsx"],
    rules: {
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },
  {
    // Tailwind's config loads plugins with require() by design.
    files: ["*.config.{ts,js}"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
);
